services:
  postgres:
    image: postgres:15
    container_name: mcp-chat-postgres
    environment:
      POSTGRES_DB: mcp_chat
      POSTGRES_USER: mcp_user
      POSTGRES_PASSWORD: mcp_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mcp_user -d mcp_chat"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
